type: CustomSearcher
args:
  num_selected: 5
  search_api_url: "http://localhost:4567/search"
  dataset_name: ["Cohere___wikipedia-2023-11-embed-multilingual-v3"]
  dataset_split: "train"
    #cache_dir: "/mnt/nfs/home/dpetresc/coherepedia-jvector/Cohere___wikipedia-2023-11-embed-multilingual-v3"
